/**
 * lib/format/_format_lint.test.ts · one way to write a number down.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THE SIBLING
 *
 * `lib/conservation/_reader_lint.test.ts` polices WHICH number a surface
 * prints — that every surface printing a run reaches `reconcileRun` rather
 * than picking its own rung off a COALESCE ladder. This polices HOW that
 * number is written down, which is a separate question that was answered
 * separately in 132 places.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THE FAILURE THIS EXISTS FOR
 *
 * `app/api/v5/today/route.ts` reads one distance at :587 and hands the SAME
 * float to two composers. On 2026-08-24 they printed:
 *
 *     lib/faff/v5-today.ts   Math.round(mi * 10) / 10   →  "3.1 mi"
 *     lib/coach/run-recap.ts (3.05).toFixed(1)          →  "3.0 mi"
 *
 * on the poster and the recap, one above the other, in one response. Both
 * idioms are ordinary and both look right. They differ because 3.05 is
 * really 3.0499999999999998, and the two roundings resolve it opposite ways.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WHAT IT SCANS FOR
 *
 * Two idioms, because those are the two that produced the split:
 *
 *   1 · `.toFixed(1)` applied to something mile-shaped. The recap side.
 *   2 · `Math.round(x * 10) / 10`. The poster side.
 *
 * And one shape, because it is a live defect in most of the copies:
 *
 *   3 · a clock or pace built by flooring the minutes and rounding the
 *       seconds SEPARATELY, which prints `6:60/mi` at 419.6 s/mi. Only
 *       `run-recap.ts` had ever noticed; `lib/format/run.ts` now rounds
 *       first for everyone.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * BOTH DIRECTIONS ARE ENFORCED
 *
 * Adding a file to `ALLOW` to silence a new violation is one line and
 * visible in review. Leaving a file on `ALLOW` after migrating it fails the
 * staleness check, exactly as the reader lint and the doctrine registry's
 * `exempt` map work. The list may shrink. It may not grow quietly.
 */
import fs from 'node:fs';
import path from 'node:path';
import { describe, it, expect } from 'vitest';
import {
  roundTo, miNum, fmtMi, fmtMi2,
  fmtPace, fmtPaceSlash, fmtPaceBand,
  fmtClock, fmtFinish, fmtDelta,
} from './run';

const WEB = path.resolve(__dirname, '..', '..');
const ROOTS = ['lib', 'app'];

/** The module itself — it must name these idioms in order to be them. */
const FORMAT_MODULE = 'lib/format/run.ts';

/** Every spelling that reaches the one formatter. A surface calling any of
 *  these is wired; one calling none is writing its own rule. */
const SHARED_FORMAT_CALLS = [
  'roundTo(', 'miNum(', 'fmtMi(', 'fmtMi2(',
  'fmtPace(', 'fmtPaceSlash(', 'fmtPaceBand(',
  'fmtClock(', 'fmtFinish(', 'fmtDelta(',
];

/**
 * Pre-existing call sites, each with an honest reason. This is the queue.
 * Migrating 132 formatters at once is its own risk; the runner-facing ones
 * that print a run went first because they are where the split was visible.
 */
/**
 * Pre-existing sites, each with an honest reason. This is the QUEUE, and it
 * is long on purpose: migrating 67 files at once is its own risk. The
 * runner-facing surfaces that print one run went first, because that is
 * where the poster and the recap disagreed in front of the owner.
 *
 * Every entry is a place a number can still be written down a second way.
 * Generated by running the detector over the tree, so nothing is listed that
 * the scan does not actually fire on — a reason attached to a file that has
 * no violation is how an allowlist rots into decoration.
 */
const ALLOW: Record<string, string> = {
  "app/api/cron/notifications/route.ts":
    "API ROUTE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "app/api/ingest/health/route.ts":
    "API ROUTE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "app/api/race/[slug]/autofill/route.ts":
    "API ROUTE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "app/api/runs/[id]/recap/route.ts":
    "API ROUTE · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "app/api/today/skip/route.ts":
    "API ROUTE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "app/api/v5/today/route.ts":
    "API ROUTE · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "app/dev/route-map-mockups/route.ts":
    "DEV-ONLY mockup route.",
  "app/sim/plan/page.tsx":
    "THE PLAN SIMULATOR · an internal tool, deliberately independent of the app it simulates.",
  "app/training/plans/[planId]/diff/page.tsx":
    "PAGE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/acknowledge.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/calibration.ts":
    "COACH COPY · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/coach-log.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/fact-reciter.ts":
    "THE NEXT ONE TO TAKE. The coach fact lines carry seven open-coded one-decimal distances — the recap's losing side of the 3.05 split, on a surface the runner reads.",
  "lib/coach/health-actions.ts":
    "COACH COPY · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/health-state.ts":
    "COACH COPY · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/heat-acclimatization.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/heat-gate.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/limiter.ts":
    "COACH COPY · a fixed-one-decimal distance (the recap rounding) and a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/morning-brief.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/race-replacement.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/races-state.ts":
    "COACH COPY · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/readiness-brief.ts":
    "COACH COPY · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/readiness.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/recovery-phase.ts":
    "COACH COPY · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/run-win.ts":
    "COACH COPY · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/state-loader.ts":
    "COACH COPY · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/coach/training-state.ts":
    "COACH COPY · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/conservation/laws.ts":
    "THE AUDIT HARNESS, and it must NOT migrate. Its header states the rule: a harness that checks the app's output may not borrow the code under test, or it proves only that the code agrees with itself. Its `fmtMi` even disagrees with the app's on whole numbers (`3.0 mi` vs `3 mi`) — if the two silently converged it would stop being able to catch a formatting regression.",
  "lib/doctrine/registry.ts":
    "THE DOCTRINE REGISTRY · formats numbers into claim failure messages for the gate, not for a runner.",
  "lib/faff/week-mileage.ts":
    "FAFF SURFACE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/notifications/session-moved.ts":
    "NOTIFICATION COPY · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/notifications/templates.ts":
    "NOTIFICATION COPY · a fixed-one-decimal distance (the recap rounding) and an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/adaptive-ramp.ts":
    "PLAN-SIDE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/block-preview.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/catalogue-rx.ts":
    "PLAN-SIDE · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/core.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/dose-guard.ts":
    "PLAN-SIDE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/drift-monitor.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/generate.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/pace-zones.ts":
    "PLAN-SIDE · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/replan-scenarios.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/simulator.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/v5-block.ts":
    "PLAN-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/plan/validate.ts":
    "PLAN VALIDATION · rounds ramp percentages for its own thresholds, never for display.",
  "lib/prescription/trajectory.ts":
    "PRESCRIPTION · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/race/execution-plan.ts":
    "RACE-SIDE · a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/race/personal-records.ts":
    "RACE-SIDE · an open-coded `Math.round(x*10)/10` (the poster rounding) and a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/race/race-detail-pacing.ts":
    "RACE-SIDE · a fixed-one-decimal distance (the recap rounding) and a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/race/representativeness.ts":
    "RACE-SIDE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/runs/flag-census.ts":
    "RUN READER · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/runs/volume.ts":
    "THE VOLUME READER · rounds weekly mileage totals, a number rather than a string.",
  "lib/strava/push.ts":
    "OUTBOUND · the description Faff posts TO Strava. A third party renders it; the shape is a wire contract, not a Faff surface.",
  "lib/today/composition.ts":
    "TODAY COMPOSITION · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/today/post-race-composition.ts":
    "TODAY COMPOSITION · a fixed-one-decimal distance (the recap rounding) and an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/aerobic-decoupling.ts":
    "TRAINING-ENGINE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/course-impact.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/expand-spec.ts":
    "TRAINING-ENGINE · a fixed-one-decimal distance (the recap rounding) and an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/fitness-trajectory.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/fueling.ts":
    "TRAINING-ENGINE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/goal-assessment.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/goal-projection.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/prescriptions.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding) and a clock split before rounding (prints `6:60`). Queued; not on the poster/recap path where the split was visible.",
  "lib/training/vdot.ts":
    "TRAINING-ENGINE · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/watch/build-workout.ts":
    "THE WATCH WIRE · these strings are rendered by the device mid-run, not by a web surface. Changing them ships on a watch build, not a web deploy.",
  "lib/weather/lookup.ts":
    "WEATHER · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/weather/openmeteo.ts":
    "WEATHER · an open-coded `Math.round(x*10)/10` (the poster rounding). Queued; not on the poster/recap path where the split was visible.",
  "lib/workout-catalogue/select.ts":
    "CATALOGUE · a fixed-one-decimal distance (the recap rounding). Queued; not on the poster/recap path where the split was visible.",
};

const rel = (p: string) => path.relative(WEB, p).split(path.sep).join('/');

function sourceFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name === 'node_modules' || e.name === '.next') continue;
        walk(p);
      } else if (/\.tsx?$/.test(e.name)
                 // `._*` are AppleDouble sidecars on this volume, not source.
                 && !e.name.startsWith('._')
                 && !/\.test\.tsx?$/.test(e.name)) {
        out.push(p);
      }
    }
  };
  for (const r of ROOTS) walk(path.join(WEB, r));
  return out;
}

/**
 * Which hand-rolled formatting idioms a file spells.
 *
 * Plain substring and small regex work, deliberately not one clever pattern.
 * A multi-line template literal defeats a line-anchored regex, and a false
 * finding was filed exactly that way in this repo. Over-reporting is the
 * right direction for a lint; under-reporting is how the split survived.
 */
function idiomsIn(src: string): string[] {
  const hits: string[] = [];

  // 1 · the recap's rounding, on something mile-shaped.
  if (/\b\w*[Mm]i\w*\.toFixed\(1\)/.test(src)
      || /\b\w*[Mm]iles\w*\.toFixed\(1\)/.test(src)) hits.push('toFixed(1) on miles');

  // 2 · the poster's rounding, open-coded.
  if (/Math\.round\([^)]*\*\s*10\s*\)\s*\/\s*10/.test(src)) hits.push('Math.round(x*10)/10');

  // 3 · minutes floored and seconds rounded separately → "6:60".
  if (/Math\.floor\([^)]*\/\s*60\s*\)/.test(src) && /Math\.round\([^)]*%\s*60\s*\)/.test(src)) {
    hits.push('split-before-round clock (prints 6:60)');
  }

  return hits;
}

describe('format lint · one way to write a run down', () => {
  it('no new file spells its own rounding rule', () => {
    const violations: string[] = [];
    for (const file of sourceFiles()) {
      const r = rel(file);
      if (r === FORMAT_MODULE || ALLOW[r]) continue;
      const hits = idiomsIn(fs.readFileSync(file, 'utf8'));
      if (hits.length > 0) violations.push(`${r} — ${hits.join(' / ')}`);
    }
    console.log(`\n=== FORMAT IDIOMS · ${Object.keys(ALLOW).length} known, ${violations.length} new ===`);
    for (const v of violations) console.log(`  ${v}`);
    expect(violations,
      'a new hand-rolled distance/pace/clock rule. Use lib/format/run.ts, or add an allowlist entry with an honest reason.',
    ).toEqual([]);
  });

  it('the allowlist has no stale entries', () => {
    const stale: string[] = [];
    for (const [file, reason] of Object.entries(ALLOW)) {
      const abs = path.join(WEB, file);
      if (!fs.existsSync(abs)) { stale.push(`${file} — file is gone (${reason})`); continue; }
      if (idiomsIn(fs.readFileSync(abs, 'utf8')).length === 0) {
        stale.push(`${file} — migrated, delete this entry (${reason})`);
      }
    }
    console.log(`\n=== ALLOWLIST STALENESS · ${stale.length} entries to delete ===`);
    for (const s of stale) console.log(`  ${s}`);
    expect(stale, 'the allowlist may shrink; a migrated file must be removed from it').toEqual([]);
  });

  it('the surfaces that print a run are wired to the shared formatter', () => {
    // The direct answer to the incident. Each of these printed a distance, a
    // clock or a pace for the SAME run in the SAME response on 2026-08-24.
    const MUST_CALL: Array<[string, string]> = [
      ['lib/faff/v5-today.ts', 'the poster'],
      ['lib/coach/run-recap.ts', 'the recap'],
      ['lib/coach/log-state.ts', 'the log'],
      ['lib/coach/run-state.ts', 'run detail'],
      ['lib/faff/glance-adapter.ts', 'the iOS briefing poster'],
      ['lib/coach/glance-state.ts', 'the briefing hero number'],
    ];
    const unwired: string[] = [];
    for (const [file, what] of MUST_CALL) {
      const src = fs.readFileSync(path.join(WEB, file), 'utf8');
      // Match on the IMPORT, not on a call. A file that aliases the shared
      // function to its old local name (`const fmtDuration = fmtClock;`) is
      // wired, and a call-shaped scan cannot see that — it would fail a
      // surface that is correctly migrated, and a lint that cries wolf gets
      // an allowlist entry rather than a fix.
      if (!src.includes("from '@/lib/format/run'")
          && !SHARED_FORMAT_CALLS.some((c) => src.includes(c))) {
        unwired.push(`${file} (${what}) reads no shared formatter`);
      }
    }
    expect(unwired, 'a surface stopped reading through the shared formatter and can drift again').toEqual([]);
  });

  it('the shared formatter is called by something other than its own tests', () => {
    // THE ASSERTION THIS FILE EXISTS FOR. The defect that opened this whole
    // line of work was a correct function with zero call sites and a green
    // unit test. A formatter nothing calls is a comment with a tick beside
    // it, and the surfaces stay exactly as wrong as they were.
    let callers = 0;
    for (const file of sourceFiles()) {
      if (rel(file) === FORMAT_MODULE) continue;
      const src = fs.readFileSync(file, 'utf8');
      if (src.includes("from '@/lib/format/run'")) callers++;
    }
    expect(callers,
      'lib/format/run.ts has no production importers — it is dead code, exactly like the guard that started this',
    ).toBeGreaterThanOrEqual(6);
  });

  it('the rounding rule is half-up on the decimal, not on the binary residue', () => {
    // The four values the two idioms disagreed on. `toFixed(1)` sends every
    // one of them DOWN because the nearest double sits just below the
    // half-way point; the runner's number is the decimal, not the double.
    expect(miNum(3.05)).toBe('3.1');
    expect(miNum(2.05)).toBe('2.1');
    expect(miNum(0.15)).toBe('0.2');
    expect(miNum(1.15)).toBe('1.2');
    // And the values both idioms already agreed on must not move.
    expect(miNum(11.05)).toBe('11.1');
    expect(miNum(12.37)).toBe('12.4');
    expect(miNum(0.84)).toBe('0.8');
    // A whole number loses its `.0` — the poster's long-standing shape.
    expect(fmtMi(6)).toBe('6 mi');
    expect(fmtMi(11.01)).toBe('11 mi');
    expect(fmtMi2(11.01)).toBe('11.01 mi');
    expect(roundTo(3.05, 1)).toBe(3.1);
    expect(roundTo(11.014, 2)).toBe(11.01);
  });

  it('a clock carries its own seconds instead of printing :60', () => {
    // 419.6 s/mi printed "6:60/mi" through every copy in the repo but one.
    expect(fmtPaceSlash(419.6)).toBe('7:00/mi');
    expect(fmtPace(419.6)).toBe('7:00');
    expect(fmtPace(419.4)).toBe('6:59');
    expect(fmtClock(3599.7)).toBe('1:00:00');
    expect(fmtClock(5298)).toBe('1:28:18');
    expect(fmtClock(2389)).toBe('39:49');
    // A finish time keeps its hour slot so a column of them sorts by eye.
    expect(fmtFinish(3593)).toBe('0:59:53');
    expect(fmtFinish(6113)).toBe('1:41:53');
    expect(fmtPaceBand(465, 490)).toBe('7:45–8:10/mi');
    expect(fmtPaceBand(465, null)).toBe('7:45/mi');
    expect(fmtDelta(72)).toBe('+1:12');
    expect(fmtDelta(0)).toBe('even');
  });

  it('refuses a number it cannot write, rather than writing a zero', () => {
    // Rule 3. A blank is an answer; "0:00/mi" and "0 mi" are not.
    for (const bad of [null, undefined, 0, -1, NaN, Infinity]) {
      expect(fmtMi(bad as number)).toBeNull();
      expect(fmtPace(bad as number)).toBeNull();
      expect(fmtClock(bad as number)).toBeNull();
      expect(fmtFinish(bad as number)).toBeNull();
    }
  });
});
