import fs from 'node:fs';
import pg from 'pg';
const env = fs.readFileSync('.env.local','utf8');
const url = (env.match(/^DATABASE_URL_RO=(.*)$/m)||[])[1];
const c = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();
const cols = await c.query(`SELECT table_name, column_name FROM information_schema.columns WHERE table_schema='public' AND (column_name ILIKE '%experience%' OR column_name ILIKE '%weekly%' OR column_name='available_days' OR column_name ILIKE '%frequency%') ORDER BY table_name, column_name`);
console.log('PROFILE-ISH COLS:', JSON.stringify(cols.rows));
const ut = await c.query(`SELECT column_name FROM information_schema.columns WHERE table_name='users' ORDER BY ordinal_position`);
console.log('users cols:', ut.rows.map(r=>r.column_name).join(','));
const tcols = await c.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND (table_name ILIKE '%profile%' OR table_name ILIKE '%setting%') ORDER BY table_name`);
console.log('profile/setting tables:', JSON.stringify(tcols.rows));
await c.end();
