import pg from 'pg'; import fs from 'fs';
const env=fs.readFileSync('.env.local','utf8');
const url=env.match(/^DATABASE_URL_RO=(.+)$/m)[1].trim().replace(/^["']|["']$/g,'');
const c=new pg.Client({connectionString:url,ssl:{rejectUnauthorized:false}}); await c.connect();
const UUID='b8b75dd8-2a04-48b4-8896-44897d9e0b25';
const r=await c.query(`SELECT slug, user_uuid, meta FROM races WHERE slug='my-5k-2026-09-13'`);
console.log('race rows for slug my-5k-2026-09-13:', r.rowCount);
for(const x of r.rows) console.log(JSON.stringify({slug:x.slug,user_uuid:x.user_uuid,date:x.meta?.date,priority:x.meta?.priority,distanceLabel:x.meta?.distanceLabel, matchesTestUser:x.user_uuid===UUID}));
const all=await c.query(`SELECT slug, user_uuid::text AS uu, meta->>'date' AS d, meta->>'priority' AS p, meta->>'distanceLabel' AS dl FROM races WHERE user_uuid=$1 ORDER BY (meta->>'date')::date DESC NULLS LAST`,[UUID]);
console.log('\nall races user_uuid='+UUID, all.rowCount);
for(const x of all.rows) console.log(x.slug,'|',x.d,'|',x.p,'|',x.dl);
await c.end();
