import fs from 'node:fs';
import pg from 'pg';
const env = fs.readFileSync('.env.local','utf8');
const url = (env.match(/^DATABASE_URL_RO=(.*)$/m)||[])[1];
const c = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();
const tu = await c.query(`SELECT u.id, u.email, u.level, u.long_run_day, u.quality_days, u.rest_day, p.experience_level, p.weekly_frequency, p.weekly_mileage_target, p.history_avg_weekly_mi FROM users u LEFT JOIN profile p ON p.user_uuid=u.id WHERE u.email='test-onboarding@faff.run'`);
console.log('TEST USER:', JSON.stringify(tu.rows));
const dup = await c.query(`SELECT user_uuid, COUNT(*) AS active_plans FROM training_plans WHERE archived_iso IS NULL GROUP BY user_uuid HAVING COUNT(*) > 1 ORDER BY active_plans DESC LIMIT 20`);
console.log('USERS WITH >1 ACTIVE PLAN:', JSON.stringify(dup.rows));
const modes = await c.query(`SELECT mode, COUNT(*) FROM training_plans WHERE archived_iso IS NULL GROUP BY mode`);
console.log('ACTIVE PLAN MODES:', JSON.stringify(modes.rows));
const mm = await c.query(`SELECT tp.id::text, tp.mode, tp.race_id, (rc.meta->>'date') AS rdate, (rc.meta->>'distanceMi') AS rdist FROM training_plans tp JOIN races rc ON rc.slug = tp.race_id WHERE tp.archived_iso IS NULL AND tp.mode='maintenance' LIMIT 30`);
console.log('MAINTENANCE PLANS:', JSON.stringify(mm.rows));
const badmeta = await c.query(`SELECT slug, (meta->>'date') AS rdate, (meta->>'distanceMi') AS rdist, (meta->>'priority') AS prio FROM races WHERE meta->>'date' IS NULL OR meta->>'distanceMi' IS NULL LIMIT 30`);
console.log('RACES MISSING date/dist (count+sample):', badmeta.rowCount, JSON.stringify(badmeta.rows.slice(0,8)));
// test user's active plans + races
const tup = await c.query(`SELECT id::text, mode, race_id, archived_iso, authored_iso FROM training_plans WHERE user_uuid=(SELECT id FROM users WHERE email='test-onboarding@faff.run') ORDER BY authored_iso DESC LIMIT 8`);
console.log('TEST USER PLANS (recent 8):', JSON.stringify(tup.rows));
const tur = await c.query(`SELECT slug, (meta->>'date') AS d, (meta->>'distanceMi') AS dist, (meta->>'priority') AS prio FROM races WHERE user_uuid=(SELECT id FROM users WHERE email='test-onboarding@faff.run') ORDER BY (meta->>'date') LIMIT 10`);
console.log('TEST USER RACES:', JSON.stringify(tur.rows));
await c.end();
