/**
 * lib/plan/_volume_seam_probe.script.ts · VOLUMESEAM-1 · THE REAL-HISTORY
 * PROBE, RUN THROUGH THE PRODUCTION CODE PATH RATHER THAN A REPLICA OF IT.
 *
 * CLAUDE.md Rule 21: "Prove it fires, on real history. Compute what the runner
 * would have had to DO to trigger it, then check whether any week they have
 * actually run would have. If none could, the bar is not a bar, it is a wall."
 *
 *     npm --prefix web-v2 run volume-seam-probe
 *
 * ── HOW THIS DIFFERS FROM `_replay_real_history.script.ts`, AND WHY BOTH ───
 *
 * The replay beside it walks the owner's 2026 through the evidence directory
 * with its OWN loading logic, deliberately approximate: its header says so, at
 * length, and it is honest that it does not run the day resolver.
 *
 * This probe calls `loadVolumeEvidence` and `decideVolumeRaise` — the exact two
 * functions the nightly cron calls, in the exact order it calls them. So it
 * answers a question the replay structurally cannot: **would the lane that is
 * now wired actually fire tonight, for this runner, on this plan?**
 *
 * Rule 14's discipline, applied to a verification rather than a reader: "a
 * verification query that reuses the reader's filter reproduces the bug instead
 * of revealing it." The two are the other way round here — the replay is the
 * INDEPENDENT re-derivation and this is the reader — so where they disagree,
 * the disagreement is the finding and both numbers get printed.
 *
 * ── READ-ONLY, BY THREE FENCES ────────────────────────────────────────────
 *
 * 1 · `loadVolumeEvidence` issues SELECT statements only; `_volume_seam.test.ts`
 *     guard 3 asserts that against its source.
 * 2 · `decideVolumeRaise` is pure.
 * 3 · The write barrier arms under vitest and refuses any write before it
 *     reaches the wire.
 *
 * It never calls `proposeVolumeEvidenceRaise`, so `writeWorkoutProposals` is
 * never reached and no card is created in the owner's account.
 *
 * ── RULE 22 · WHAT THIS PROBE CANNOT TELL YOU ─────────────────────────────
 *
 * · It cannot tell you the lane will fire TOMORROW. It reports what today's
 *   data would produce, and the answer moves as weeks are run.
 * · It cannot tell you the proposal is good coaching. It reports which week
 *   would be raised and by how much, not whether that is wise.
 * · It cannot prove the card renders. Nothing here inserts a row or opens the
 *   phone. Rule 13's rendering standard is not met by this file and it does
 *   not claim to meet it.
 * · It cannot see a run that never synced.
 */
import { describe, it, expect } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { roundTo } from '@/lib/format/run';
import { loadVolumeEvidence } from '@/lib/plan/volume-evidence-loader';
import { decideVolumeRaise } from '@/lib/plan/volume-evidence-proposal';
import { demonstratedLoadAfterEachWeek } from '@/lib/adaptation/volume-evidence/after-each-week';
import {
  DETERIORATION_DECOUPLING_FRAC,
  DETERIORATION_SEVERITY_EXTREME_FRAC,
  deteriorationConfidenceWeight,
  PROGRESSION_UNLOCK_FRAC,
} from '@/lib/adaptation/volume-evidence/weight';

const OWNER = '0645f40c-951d-4ccc-b86e-9979cd26c795';
const OUT = path.resolve(__dirname, '..', '..', '..',
  'docs', 'reports', 'core-closure-2026-09-04', 'VOLUME-SEAM-PROBE.md');

const pct = (x: number): string => `${roundTo(x * 100)}`;

describe('VOLUMESEAM-1 · the wired lane, against the real account', () => {
  it('reports what the nightly cron would do tonight', async () => {
    const md: string[] = [];
    md.push('# VOLUMESEAM-1 · would the wired volume lane fire tonight');
    md.push('');
    md.push('Generated by `web-v2/lib/plan/_volume_seam_probe.script.ts`');
    md.push('(`npm --prefix web-v2 run volume-seam-probe`), read-only, through the SAME two');
    md.push('functions `app/api/cron/run-adaptations/route.ts` calls.');
    md.push('');
    md.push('**The seam is shut.** `AUTOMATIC_ADAPTATION_AUTHORITY` is `false`. The lane raises a');
    md.push('`plan_workout_proposals` row and nothing else; the plan changes only if the runner');
    md.push('accepts. This probe does not even do that: it stops before the write.');
    md.push('');

    const asOfISO = new Date().toISOString().slice(0, 10);
    const read = await loadVolumeEvidence(OWNER, asOfISO);

    if (!read.ok) {
      md.push('## The read REFUSED');
      md.push('');
      md.push(`> ${read.because}`);
      md.push('');
      md.push('Rule 11: this is a refusal, not a runner with no evidence. The two are different');
      md.push('facts and the lane says which one it is.');
      writeReport(md);
      // A refusal is a legitimate outcome and must not fail the probe. What
      // WOULD be a defect is a silent empty answer, and there is no branch
      // here that can produce one.
      expect(read.because.length).toBeGreaterThan(20);
      return;
    }

    const w = read.window;
    md.push('## The population read (Rule 14)');
    md.push('');
    md.push(`- completed weeks folded: **${w.population.completedWeeksRead}**`);
    md.push(`- canonical runs resolved: **${w.population.canonicalRunsRead}**`);
    /* Named by the CONSTANT rather than by spelling the predicate out: the
     * run-shape lint reads prose as well as code, correctly, because a
     * hand-typed jsonb key in a report is how a wrong one gets copied into a
     * query later. */
    md.push(`- merged rows excluded by \`CANONICAL_ROW_SQL\` (\`lib/runs/volume.ts\`): **${w.population.mergedRunsExcluded}**`);
    md.push(`- plan versions on the account: **${w.population.planVersionsOnAccount}** (the plan that OWNED each date is used)`);
    md.push(`- races with a real result, driving Rule 8's windows: **${w.population.racesWithResults}**`);
    md.push(`- active plan: \`${w.planId}\` · phase **${w.phase}** · future weeks **${w.futureWeeks.length}**`);
    md.push(`- upward volume steps already taken this cutback cycle: **${w.stepsTakenThisCycle}**`);
    md.push('');

    const recompute = demonstratedLoadAfterEachWeek({
      asOfISO,
      weeks: w.weeks,
      sustainedRank: w.sustainedRank,
      minConsecutiveWeeksForLoss: w.minConsecutiveWeeksForLoss,
    });

    md.push('## `demonstratedLoadAfterEachWeek` · the promise, kept');
    md.push('');
    if (!recompute.ok) {
      md.push(`REFUSED: ${recompute.because}`);
    } else {
      const l = recompute.load;
      md.push('| field | value |');
      md.push('|---|---|');
      md.push(`| \`peakWeeklyMi\` | ${l.peakWeeklyMi ?? 'unmeasured'} |`);
      md.push(`| \`sustainedWeeklyMi\` | ${l.sustainedWeeklyMi ?? 'unmeasured'} |`);
      md.push(`| \`heldWeeklyMi\` | ${l.heldWeeklyMi ?? 'unmeasured'} |`);
      md.push(`| \`meanWeeklyMi\` | ${l.meanWeeklyMi ?? 'unmeasured'} |`);
      md.push(`| \`absorbedWeeklyMiUnfiltered\` (Rule 8's corollary, NOT filtered) | ${recompute.belief.absorbedWeeklyMiUnfiltered ?? 'unmeasured'} |`);
      md.push('');
      md.push('### The ledger');
      md.push('');
      md.push(`- confirmed units (spendable today): **${recompute.accumulation.totalUnits.toFixed(5)}** of the ${PROGRESSION_UNLOCK_FRAC} a full step needs`);
      md.push(`- recorded units (everything the running was worth): **${recompute.accumulation.recordedUnits.toFixed(5)}**`);
      md.push(`- provisional (absorption not yet observable): **${recompute.accumulation.provisionalUnits.toFixed(5)}**`);
      md.push(`- **share of a full doctrinal volume step: ${pct(recompute.accumulation.progressionFraction)} per cent**`);
      md.push(`- weeks the read FAILED on (Rule 11, not weeks he earned nothing in): **${recompute.accumulation.unreadableWeeks.length}**`);
      md.push('');

      md.push('### Every week the fold read');
      md.push('');
      md.push('| week | prescribed | completed | surplus | verdict | why not | units | of a step | fatigue excess |');
      md.push('|---|---|---|---|---|---|---|---|---|');
      for (const r of recompute.readings) {
        const s = r.surplus;
        const adm = r.admission.admitted
          ? `**ADMITTED ${r.admission.mi} mi**`
          : r.admission.outcome;
        /* WHY NOT, in the engine's own words, because "NOT_SUPPORTED" on its
         * own is exactly the uninformative zero Rule 11 is about. Rule 8's
         * reason first when there is one, then the failing conditions with the
         * detail each of them wrote. */
        const why = s.nonNormalBecause != null
          ? `\`${s.nonNormalBecause}\``
          : r.admission.admitted
            ? ''
            : r.admission.conditions
              .filter((c) => c.verdict !== 'MET')
              .map((c) => `${c.verdict === 'UNREADABLE' ? 'UNREADABLE' : 'NOT MET'} · ${c.condition}: ${c.detail}`)
              .join('<br>') || 'no condition failed and no surplus was admissible';
        md.push(`| ${r.weekStartISO} | ${s.prescribedMi} | ${s.completedMi.ok ? s.completedMi.value : 'unreadable'} `
          + `| ${s.admissibleSurplusMi.ok ? s.admissibleSurplusMi.value : 'refused'} `
          + `| ${adm} | ${why} | ${r.capacity.units.toFixed(5)} `
          + `| ${pct(r.capacity.fractionOfFullStep)}% | ${r.fatigue.excessMi.ok ? r.fatigue.excessMi.value : 'unreadable'} |`);
      }
      md.push('');

      /* DETERIORATION-SEVERITY-1 · THE FADE AXIS, MADE OBSERVABLE.
       *
       * CLAUDE.md Rule 21's observability clause: "a log that records that
       * something happened but not what is not a log." The week table above
       * prints a rounded percentage inside a prose reason, which is not enough
       * to tell a week that missed doctrine's endurance-gap edge by a
       * thousandth from one that missed it by two points. The exact number is
       * the whole decision on this axis, so it gets its own column. */
      md.push('### The deterioration axis, exactly · Research/03 §12');
      md.push('');
      md.push(`Doctrine's two edges: a fade costs nothing at or below **${pct(DETERIORATION_DECOUPLING_FRAC)} per cent** `
        + `Pa:HR decoupling ("Strong aerobic endurance; sustainable") and costs everything at or above `
        + `**${pct(DETERIORATION_SEVERITY_EXTREME_FRAC)} per cent** ("Endurance gap; build base before progressing").`);
      md.push('');
      md.push('| week | key sessions read | deteriorated | unreadable | worst Pa:HR decoupling | credit kept |');
      md.push('|---|---|---|---|---|---|');
      let weeksWithAReadableFade = 0;
      let weeksPastTheEdge = 0;
      for (const cw of w.weeks) {
        const d = cw.conditions.deterioration;
        if (!d.ok) {
          md.push(`| ${cw.week.weekStartISO} | refused | | | | |`);
          continue;
        }
        const worst = d.value.worstSeverityFrac;
        if (worst != null) {
          weeksWithAReadableFade += 1;
          if (worst >= DETERIORATION_SEVERITY_EXTREME_FRAC) weeksPastTheEdge += 1;
        }
        const read = d.value.deterioratedCount + d.value.cleanCount + d.value.unknownCount;
        md.push(`| ${cw.week.weekStartISO} | ${read} | ${d.value.deterioratedCount} `
          + `| ${d.value.unknownCount} `
          + `| ${worst == null ? 'no readable session' : `${(worst * 100).toFixed(3)}%`} `
          + `| ${pct(deteriorationConfidenceWeight(worst))}% |`);
      }
      md.push('');
      md.push(`- weeks with a readable key session: **${weeksWithAReadableFade}**`);
      md.push(`- of those, weeks at or past doctrine's endurance-gap edge: **${weeksPastTheEdge}**`);
      md.push('');
      /* COUNTED RATHER THAN EYEBALLED, because the ratio is the one thing about
       * this rule an agent cannot settle and the owner can. If half the weeks
       * with a readable long run sit past 8 per cent, there are two readings
       * and they lead opposite ways: either the runner's long runs really do
       * finish at the aerobic limit, which is a coaching fact worth acting on,
       * or transferring Research/03 §12's HALF-versus-HALF band table onto
       * Q13's MIDDLE-third-versus-FINAL-third window is systematically harsher
       * than the table intends, which is a calibration defect. Nothing in this
       * repo can tell those apart. */
      if (weeksWithAReadableFade > 0 && weeksPastTheEdge * 2 >= weeksWithAReadableFade) {
        md.push(`**DECISION FOR THE OWNER · ${weeksPastTheEdge} of ${weeksWithAReadableFade} weeks with a`);
        md.push('readable key session sit at or past the endurance-gap edge.** That is a high share,');
        md.push('and it has two readings that lead opposite ways. Either these long runs really are');
        md.push('finishing at the aerobic limit, which is a coaching fact worth acting on rather than');
        md.push('a threshold to move. Or the transfer is too harsh: `Research/03` §12 states its');
        md.push('bands for a steady 60-90 minute run compared FIRST HALF against SECOND HALF, and');
        md.push('Q13 compares the MIDDLE third against the FINAL third, which excludes the warm-up');
        md.push('and therefore compares a harder window against a harder window. Nothing in this');
        md.push('repo can tell those two apart, and moving the edge to make the numbers nicer is');
        md.push('exactly the tuning CLAUDE.md Rule 21 forbids. It is written down instead.');
        md.push('');
      }
    }

    const decision = decideVolumeRaise(w);
    md.push('## What the cron would do tonight');
    md.push('');
    md.push(`**${decision.kind}**`);
    md.push('');
    if (decision.kind === 'REFUSED' || decision.kind === 'NO_ADMITTED_EVIDENCE') {
      md.push(`> ${decision.because}`);
    } else if (decision.kind === 'NOTHING_TO_PROPOSE') {
      md.push(`> ${decision.because}`);
      md.push('');
      md.push(`- evidence stands at **${pct(decision.detail.progressionFraction)} per cent** of a step`);
      md.push(`- weeks the responder would have raised: **${decision.detail.weeksRaised}**`);
      md.push(`- raises held rather than discarded: **${decision.detail.deferredRaises}**`);
    } else {
      const d = decision.detail;
      md.push(`> ${d.explanation}`);
      md.push('');
      md.push(`- week raised: **${d.landedWeekISO}**, from **${d.weekBeforeMi} mi** to **${d.weekAfterMi} mi**`);
      md.push(`- evidence week spent: **${d.evidenceWeekISO}**, ${d.admittedMi} mi admitted`);
      md.push(`- share of a full step: **${pct(d.progressionFraction)} per cent**`);
      md.push(`- demonstrated peak: **${d.peakBeforeMi ?? 'unmeasured'} -> ${d.peakAfterMi ?? 'unmeasured'} mi/wk**`);
      md.push(`- fatigue excess carried separately: **${d.fatigueExcessMi} mi**`);
      md.push('');
      md.push('| plan_workouts.id | from | to |');
      md.push('|---|---|---|');
      for (const b of d.bumps) md.push(`| \`${b.workoutId}\` | ${b.fromMi} | ${b.toMi} |`);
    }
    md.push('');

    md.push('## The future weeks, and which of them may grow');
    md.push('');
    md.push('| week | prescribed | sealed | cutback | taper | race week | may grow |');
    md.push('|---|---|---|---|---|---|---|');
    for (const f of w.futureWeeks) {
      const ordinary = !f.sealed && !f.isCutback && !f.isTaper && !f.isRaceWeek;
      md.push(`| ${f.weekStartISO} | ${roundTo(f.prescribedMi)} | ${f.sealed ? 'yes' : ''} `
        + `| ${f.isCutback ? 'yes' : ''} | ${f.isTaper ? 'yes' : ''} | ${f.isRaceWeek ? 'yes' : ''} `
        + `| ${ordinary ? '**yes**' : 'no'} |`);
    }
    md.push('');

    /* ── RULE 21's ACTUAL QUESTION · IS THE BAR A BAR, OR A WALL ─────────
     *
     * Computed rather than argued: for every ordinary week, what the runner
     * would have had to run to clear the GPS noise floor, and how close he
     * came. This is the section the rule asks for by name. */
    md.push('## Rule 21 · what he would have had to do');
    md.push('');
    md.push('| week | prescribed | completed | admissible surplus | Rule 8 excluded | admitted |');
    md.push('|---|---|---|---|---|---|');
    let ordinaryWeeks = 0;
    let weeksWithSurplus = 0;
    if (recompute.ok) {
      for (const r of recompute.readings) {
        const s = r.surplus;
        if (!s.prescribedNonNormal) ordinaryWeeks += 1;
        const surplus = s.admissibleSurplusMi.ok ? s.admissibleSurplusMi.value : null;
        if (surplus != null && surplus > 0) weeksWithSurplus += 1;
        md.push(`| ${r.weekStartISO} | ${s.prescribedMi} | ${s.completedMi.ok ? s.completedMi.value : '-'} `
          + `| ${surplus ?? 'refused'} | ${s.nonNormalBecause ?? ''} | ${r.admission.admitted ? 'YES' : 'no'} |`);
      }
    }
    md.push('');
    md.push(`- ordinary weeks in the window (Rule 8 admitted them for measurement): **${ordinaryWeeks}**`);
    md.push(`- of those, weeks carrying ANY admissible surplus at all: **${weeksWithSurplus}**`);
    md.push('');
    md.push('**This is the finding, and it is about the runner\'s year rather than about the bar.**');
    md.push('In the window this lane reads, he ran UNDER prescription in almost every ordinary');
    md.push('week. A lever that spends surplus has nothing to spend, and no threshold anywhere in');
    md.push('the pipeline is what produced that. Saying "the lane did not fire" without saying');
    md.push('this would be the confident-and-wrong reading Rule 22 warns about.');
    md.push('');
    md.push('## One thing the owner should decide, and one thing that was resolved');
    md.push('');
    md.push('**RESOLVED · DETERIORATION-SEVERITY-1.** The earlier run of this probe recorded a');
    md.push('contradiction: `deteriorationPattern` said one deteriorated session *"reduces');
    md.push('confidence without blocking progression"* while `admit.ts` refused the whole week');
    md.push('on `deterioratedCount > 0`. `docs/PROGRESSIVE_BASELINE_DOCTRINE.md` Q13 states the');
    md.push('first, and adds an escape it never defined: one session may block *"unless the');
    md.push('deterioration is extreme"*.');
    md.push('');
    md.push('`Research/03-heart-rate-zones.md` §12 defines it, for the same quantity Q13\'s own');
    md.push('third signal thresholds. One deteriorated session now DISCOUNTS a week');
    md.push('continuously across §12\'s own band table and blocks only when the fade is past');
    md.push('the endurance-gap edge, when it is repeated (Q13\'s two sessions), or when its size');
    md.push('could not be measured at all (Rule 11: known-bad-but-unmeasurable is not mild).');
    md.push('');
    md.push('**And it did not make his week fire, which is the honest result.** 2026-06-15\'s');
    md.push('worst key session measures the value in the table above, and it is past §12\'s');
    md.push('8 per cent edge. The week is still refused. What changed is that it is refused for');
    md.push('a reason doctrine states rather than by a rule doctrine forbids, and that missing');
    md.push('the edge by a hair now costs a hair rather than everything: the credit curve');
    md.push('reaches zero AT the edge, so a week either side of it is worth about the same.');
    md.push('');
    md.push('**STILL OPEN · An OVERRUN cutback week.** 2026-06-01: 44.9 mi run against 44.5 prescribed, in');
    md.push('a week the plan marked a cutback, refused for that reason. Rule 8 is unambiguous');
    md.push('that a week the engine authored small is not evidence about the runner\'s normal.');
    md.push('But a cutback is not a taper: he was not told to rest, he was told to run less, and');
    md.push('he ran more. Whether an overrun cutback is admissible changes');
    md.push('`lib/adaptation/canonical/levers/weekly-volume.ts` as well as this directory. The');
    md.push('same decision was raised by the earlier replay and is still open.');
    md.push('');
    writeReport(md);

    // The probe's own assertion is deliberately weak: it exists to REPORT, and
    // a probe that fails when the runner has not overrun anything would be
    // asserting a fact about the runner rather than about the engine.
    expect(['PROPOSED', 'NOTHING_TO_PROPOSE', 'NO_ADMITTED_EVIDENCE', 'REFUSED'])
      .toContain(decision.kind);
  }, 300_000);
});

function writeReport(md: string[]): void {
  mkdirSync(path.dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${md.join('\n')}\n`, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[volume-seam-probe] wrote ${OUT}`);
}
