import pg from 'pg';
import fs from 'fs';
const env = fs.readFileSync('.env.local','utf8').split('\n').reduce((a,l)=>{const m=l.match(/^([A-Z_]+)=(.*)$/);if(m)a[m[1]]=m[2].replace(/^["']|["']$/g,'');return a;},{});
const pool = new pg.Pool({ connectionString: env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const DAVID = '0645f40c-951d-4ccc-b86e-9979cd26c795';
const r1 = await pool.query("SELECT provider, last_sync_at, expires_at, refresh_token IS NOT NULL AS has_refresh FROM connector_tokens WHERE user_uuid = $1 OR user_id = $1", [DAVID]);
console.log('connector_tokens:');
for (const row of r1.rows) console.log('  ' + row.provider + ' · last_sync=' + row.last_sync_at + ' · refresh=' + row.has_refresh);
const r2 = await pool.query("SELECT data->>'source' AS source, COUNT(*) AS n FROM runs WHERE user_uuid = $1 AND (data->>'date')::date >= CURRENT_DATE - 30 GROUP BY 1", [DAVID]);
console.log('\nsources last 30d:');
for (const row of r2.rows) console.log('  ' + row.source + ' · ' + row.n);
const r3 = await pool.query("SELECT data->>'date' AS date, data->>'source' AS src, data->>'mergedIntoId' AS merged_into, (data->>'distanceMi')::numeric AS mi FROM runs WHERE user_uuid = $1 AND data ? 'mergedIntoId' ORDER BY (data->>'date')::date DESC LIMIT 5", [DAVID]);
console.log('\nrecent merged-out rows:');
for (const row of r3.rows) console.log('  ' + row.date + ' · src=' + row.src + ' · mi=' + row.mi + ' · into=' + row.merged_into);
const r4 = await pool.query("SELECT column_name FROM information_schema.columns WHERE table_name = 'shoes' ORDER BY ordinal_position");
console.log('\nshoes columns:', r4.rows.map(c => c.column_name).join(', '));
await pool.end();
