import { notFound } from 'next/navigation';
import { buildRaceDetail } from '@/components/faff-app/raceDetail';
import { RaceDetailClient } from '@/components/redesign/races/RaceDetailClient';

export const dynamic = 'force-dynamic';

/**
 * app/redesign/races/[slug]/page.tsx
 *
 * The redesigned Race Detail screen. Same real data path as the live
 * /goal/[slug] route — no new data loader:
 *
 *   · components/faff-app/raceDetail.ts#buildRaceDetail(slug) — called
 *     directly, server-side, exactly like the live /goal/[slug]/page.tsx
 *     does. buildRaceDetail already resolves userId from the faff_session
 *     cookie internally and returns null on "not signed in" / "not your
 *     race" (both surface as 404, matching the live route's own auth
 *     posture — see raceDetail.ts's own docstring on the 2026-05-30 P1
 *     SSR-leak fix). The live route instead mounts the Shell + RaceView
 *     client component so the same view can also open from the Season
 *     hero; this route only ever renders the standalone page, so calling
 *     the loader directly is the more direct equivalent.
 *
 *   · buildRaceDetail already implements the race-data source-of-truth
 *     doctrine (CLAUDE.md "Race-data source-of-truth"): finishTime comes
 *     from loadRacesState's resolution of races.actual_result (curated
 *     chip time) before any Strava fallback, and any Strava-sourced
 *     provisional finish is carried through r.finishProvisional /
 *     r.finishProvisionalLabel so the client can label it, never render it
 *     as an authoritative result. This route consumes RaceDetailSeed
 *     as-is — it does not re-derive or re-resolve any race-result field.
 *
 * Route param: [slug], not [id]. Race slugs are server-generated by
 * app/api/race/route.ts's slugify() — `s.toLowerCase().replace(/[^a-z0-9]+/g,
 * '-')` — which can never produce a literal '#'. That rules out the
 * Next 15 dynamic-segment '#'-in-param decode gap RunDetailClient's route
 * had to guard against (run ids carry a watch-sync "YYYY-MM-DD#HHmm"
 * suffix; race slugs cannot). Verified against the slugify source rather
 * than assumed — no decode guard needed here.
 */
export default async function RedesignRaceDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const race = await buildRaceDetail(slug);
  if (!race) notFound();

  return (
    <div className="redesign-root" data-theme="light">
      <RaceDetailClient race={race} />
    </div>
  );
}
