-- workout_library snapshot 2026-08-28 · 54 rows, taken before owner-approved DROP (migration 158).
-- The rows live on verbatim in web-v2/lib/plan/workout-library-static.ts (5,320-combination equivalence proven).
-- Restore: recreate via db/migrations/125_workout_library.sql, then run these INSERTs.
--                                              Table "public.workout_library"
--          Column         |           Type           | Collation | Nullable |                   Default                   
-- ------------------------+--------------------------+-----------+----------+---------------------------------------------
--  id                     | bigint                   |           | not null | nextval('workout_library_id_seq'::regclass)
--  slug                   | text                     |           | not null | 
--  name                   | text                     |           | not null | 
--  family                 | text                     |           | not null | 
--  distance_focus         | text[]                   |           | not null | '{}'::text[]
--  phase_fit              | text[]                   |           | not null | '{}'::text[]
--  level_fit              | text[]                   |           | not null | '{}'::text[]
--  pace_zones             | text[]                   |           | not null | '{}'::text[]
--  is_quality             | boolean                  |           | not null | false
--  is_long                | boolean                  |           | not null | false
--  typical_duration_min   | int4range                |           |          | 
--  typical_distance_mi    | numrange                 |           |          | 
--  frequency_max_per_week | integer                  |           | not null | 1
--  structure              | jsonb                    |           | not null | 
--  prescription_text      | text                     |           | not null | 
--  notes                  | text                     |           |          | 
--  warmup_cooldown        | text                     |           |          | 
--  citation               | text                     |           | not null | 
--  active                 | boolean                  |           | not null | true
--  updated_ts             | timestamp with time zone |           | not null | now()
-- Indexes:
--     "workout_library_pkey" PRIMARY KEY, btree (id)
--     "workout_library_distance_idx" gin (distance_focus)
--     "workout_library_family_idx" btree (family) WHERE active
--     "workout_library_level_idx" gin (level_fit)
--     "workout_library_phase_idx" gin (phase_fit)
--     "workout_library_quality_long_idx" btree (is_quality, is_long) WHERE active
--     "workout_library_slug_key" UNIQUE CONSTRAINT, btree (slug)
-- Check constraints:
--     "workout_library_family_check" CHECK (family = ANY (ARRAY['recovery'::text, 'easy'::text, 'medium_long'::text, 'long'::text, 'threshold'::text, 'vo2max'::text, 'speed'::text, 'hills'::text, 'fartlek'::text, 'combo'::text, 'marathon_specific'::text, 'cutdown'::text, 'ladder'::text, 'race_specific'::text, 'base_building'::text, 'maintenance'::text, 'walk_run'::text, 'race'::text, 'shakeout'::text, 'rest'::text]))
-- 
INSERT INTO workout_library VALUES (1,recovery-run-20-45,"Recovery run",recovery,{all},"{base,build,quality,race_specific,taper,race_week,maintenance}","{intermediate,advanced,advanced_plus}",{E},f,f,"[20,46)","[2,5]",3,"{""type"": ""recovery"", ""hr_cap_pct_max"": 70, ""pace_below_easy"": true}","20–45 min recovery jog","Easier than easy. Day after a hard session. Skip if RHR >7 bpm above baseline.","None — keep the whole thing easy.","Research/04-workout-vocabulary.md §1",t,"2026-05-31 03:40:08.660202+00");
INSERT INTO workout_library VALUES (2,easy-30,"Easy run (30 min)",easy,{all},"{base,build,quality,race_specific,taper,race_week,maintenance}","{beginner,intermediate,advanced,advanced_plus}",{E},f,f,"[25,36)","[3,5]",5,"{""type"": ""easy"", ""hr_zone"": ""Z2"", ""conversational"": true}","30 min easy","Conversational. Z2 HR cap. Bulk-volume building block.",,"Research/04-workout-vocabulary.md §2",t,"2026-05-31 03:40:08.755989+00");
INSERT INTO workout_library VALUES (3,easy-45,"Easy run (45 min)",easy,{all},"{base,build,quality,race_specific,taper,maintenance}","{intermediate,advanced,advanced_plus}",{E},f,f,"[40,51)","[4,6]",5,"{""type"": ""easy"", ""conversational"": true}","45 min easy","Conversational. Standard weekday mid-distance easy.",,"Research/04-workout-vocabulary.md §2",t,"2026-05-31 03:40:08.847987+00");
INSERT INTO workout_library VALUES (4,easy-60,"Easy run (60 min)",easy,{all},"{base,build,quality,race_specific,maintenance}","{intermediate,advanced,advanced_plus}",{E},f,f,"[55,71)","[6,8]",3,"{""type"": ""easy"", ""conversational"": true}","60 min easy","Conversational. Common second-longest weekday run.",,"Research/04-workout-vocabulary.md §2",t,"2026-05-31 03:40:08.937991+00");
INSERT INTO workout_library VALUES (5,easy-plus-strides,"Easy + 6 strides",easy,{all},"{base,build,quality,race_specific,taper,maintenance}","{beginner,intermediate,advanced,advanced_plus}","{E,R}",f,f,"[35,56)","[4,6]",2,"{""type"": ""easy_plus_strides"", ""strides"": {""count"": 6, ""recovery"": ""full_walk"", ""pace_zone"": ""R"", ""distance_m"": 80}}","45 min easy + 6×80m strides","End of an easy run. Relaxed mile-to-5K pace. Full walk between. Never skip strides — keep neuromuscular sharpness.",,"Research/04-workout-vocabulary.md §7.2",t,"2026-05-31 03:40:09.029191+00");
INSERT INTO workout_library VALUES (6,medium-long-12,"Medium-long run (12 mi)",medium_long,"{hm,m}","{build,quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,M}",f,f,"[90,121)","[11,13]",1,"{""type"": ""medium_long"", ""bulk_pace"": ""E"", ""optional_M_segment_mi"": 0}","12 mi medium-long (E)","Bridges weekday easy and the weekend long run. Pfitzinger MLR. Don't race it.",,"Research/04-workout-vocabulary.md §3",t,"2026-05-31 03:40:09.121275+00");
INSERT INTO workout_library VALUES (7,medium-long-14,"Medium-long run (14 mi)",medium_long,"{hm,m}","{quality,race_specific}","{advanced,advanced_plus}","{E,M}",f,f,"[105,136)","[13,15]",1,"{""type"": ""medium_long"", ""bulk_pace"": ""E""}","14 mi medium-long (E)","Pfitz peak-volume MLR. Sometimes appended with 6×ST.",,"Research/04-workout-vocabulary.md §3",t,"2026-05-31 03:40:09.214982+00");
INSERT INTO workout_library VALUES (8,long-base-90min,"Base long run (90 min)",long,"{5k,10k,hm,m}","{base,build}","{intermediate,advanced,advanced_plus}",{E},f,t,"[85,101)","[8,12]",1,"{""pace"": ""E"", ""type"": ""base_long"", ""conversational"": true}","90 min long (all E)","Pure aerobic stimulus. Build the engine. Cap at 25% of weekly mileage for marathoners.",,"Research/04-workout-vocabulary.md §4.2",t,"2026-05-31 03:40:09.30642+00");
INSERT INTO workout_library VALUES (9,long-base-16mi,"Base long run (16 mi)",long,"{hm,m}","{build,quality}","{intermediate,advanced,advanced_plus}",{E},f,t,"[135,166)","[15,17]",1,"{""pace"": ""E"", ""type"": ""base_long""}","16 mi long (E)","Marathon-block staple. Conversational throughout.",,"Research/04-workout-vocabulary.md §4.2",t,"2026-05-31 03:40:09.397368+00");
INSERT INTO workout_library VALUES (10,long-base-20mi,"Base long run (20 mi)",long,{m},"{quality,race_specific}","{intermediate,advanced,advanced_plus}",{E},f,t,"[165,211)","[19,21]",1,"{""pace"": ""E"", ""type"": ""base_long""}","20 mi long (E)","Marathon peak long. 3–4 times in a cycle is sufficient.",,"Research/04-workout-vocabulary.md §4.2",t,"2026-05-31 03:40:09.490371+00");
INSERT INTO workout_library VALUES (11,long-progression-16,"Progression long run (16 mi: 6E + 6M + 4T)",long,"{hm,m}",{race_specific},"{intermediate,advanced,advanced_plus}","{E,M,T}",t,t,"[120,141)","[15,17]",1,"{""type"": ""progression_long"", ""blocks"": [{""miles"": 6, ""pace_zone"": ""E""}, {""miles"": 6, ""pace_zone"": ""M""}, {""miles"": 4, ""pace_zone"": ""T""}]}","16 mi progression: 6 mi E + 6 mi M + 4 mi T","Train pace tolerance under fatigue. Continuous — no walk breaks. Skip if accumulated fatigue is high.",,"Research/04-workout-vocabulary.md §4.3",t,"2026-05-31 03:40:09.581096+00");
INSERT INTO workout_library VALUES (12,long-mp-16,"Marathon-pace long run (16 mi w/ 12 @ MP)",long,{m},{race_specific},"{intermediate,advanced,advanced_plus}","{E,MP}",t,t,"[120,141)","[15,17]",1,"{""type"": ""mp_long"", ""blocks"": [{""label"": ""warmup"", ""miles"": 2, ""pace_zone"": ""E""}, {""miles"": 12, ""pace_zone"": ""MP""}, {""label"": ""cooldown"", ""miles"": 2, ""pace_zone"": ""E""}]}","16 mi: 2E + 12 @ MP + 2E","Marathon-specific stimulus. MP exact — not faster. Every 2–3 weeks 6–10 weeks out.",,"Research/04-workout-vocabulary.md §4.4",t,"2026-05-31 03:40:09.672423+00");
INSERT INTO workout_library VALUES (13,long-mp-20,"Marathon-pace long run (20 mi w/ 14 @ MP)",long,{m},{race_specific},"{advanced,advanced_plus}","{E,MP}",t,t,"[165,196)","[19,21]",1,"{""type"": ""mp_long"", ""blocks"": [{""label"": ""warmup"", ""miles"": 3, ""pace_zone"": ""E""}, {""miles"": 14, ""pace_zone"": ""MP""}, {""label"": ""cooldown"", ""miles"": 3, ""pace_zone"": ""E""}]}","20 mi: 3E + 14 @ MP + 3E","Peak marathon-specific session. 2× in a cycle is typical.",,"Research/04-workout-vocabulary.md §4.4",t,"2026-05-31 03:40:09.765398+00");
INSERT INTO workout_library VALUES (14,long-fast-finish-14,"Fast-finish long run (14 mi w/ last 3 @ MP)",long,"{hm,m}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,MP}",t,t,"[105,126)","[13,15]",1,"{""type"": ""fast_finish_long"", ""blocks"": [{""miles"": 11, ""pace_zone"": ""E""}, {""label"": ""fast finish"", ""miles"": 3, ""pace_zone"": ""MP""}]}","14 mi: 11 E, last 3 @ MP","Train ability to find pace late. Mental rehearsal of ""the last 10K.""",,"Research/04-workout-vocabulary.md §4.5",t,"2026-05-31 03:40:09.855843+00");
INSERT INTO workout_library VALUES (15,long-dress-rehearsal-20,"Dress-rehearsal long run (20 mi w/ MP segments)",long,{m},{race_specific},"{intermediate,advanced,advanced_plus}","{E,MP}",t,t,"[150,176)","[19,21]",1,"{""type"": ""dress_rehearsal"", ""blocks"": [{""label"": ""warmup"", ""miles"": 6, ""pace_zone"": ""E""}, {""label"": ""segment 1"", ""miles"": 4, ""pace_zone"": ""MP""}, {""label"": ""recovery"", ""miles"": 3, ""pace_zone"": ""E""}, {""label"": ""segment 2"", ""miles"": 4, ""pace_zone"": ""MP""}, {""label"": ""cooldown"", ""miles"": 3, ""pace_zone"": ""E""}], ""race_day_simulation"": {""kit"": true, ""fueling"": true, ""breakfast"": true}}","20 mi w/ 2×4 mi @ MP — full kit + fuel rehearsal","3 weeks pre-marathon. Race-day breakfast, kit, fueling. Skip MP if any niggle flagging.",,"Research/04-workout-vocabulary.md §4.6",t,"2026-05-31 03:40:09.946373+00");
INSERT INTO workout_library VALUES (16,tempo-continuous-4,"Continuous tempo (4 mi @ T)",threshold,"{5k,10k,hm,m}","{build,quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,T}",t,f,"[50,66)","[7,9]",1,"{""type"": ""continuous_tempo"", ""blocks"": [{""label"": ""WU"", ""miles"": 2, ""pace_zone"": ""E""}, {""miles"": 4, ""pace_zone"": ""T""}, {""label"": ""CD"", ""miles"": 2, ""pace_zone"": ""E""}]}","2 mi WU · 4 mi @ T · 2 mi CD","""Comfortably hard"" — sustainable for ~1 hr in a race. Skip if HR/perceived effort elevated.","2 mi E each side","Research/04-workout-vocabulary.md §5.2",t,"2026-05-31 03:40:10.037145+00");
INSERT INTO workout_library VALUES (17,tempo-continuous-6,"Continuous tempo (6 mi @ T)",threshold,"{hm,m}","{quality,race_specific}","{advanced,advanced_plus}","{E,T}",t,f,"[70,86)","[10,12]",1,"{""type"": ""continuous_tempo"", ""blocks"": [{""label"": ""WU"", ""miles"": 2, ""pace_zone"": ""E""}, {""miles"": 6, ""pace_zone"": ""T""}, {""label"": ""CD"", ""miles"": 2, ""pace_zone"": ""E""}]}","2 mi WU · 6 mi @ T · 2 mi CD","~36 min at T. Backbone of HM/M training.","2 mi E each side","Research/04-workout-vocabulary.md §5.2",t,"2026-05-31 03:40:10.128598+00");
INSERT INTO workout_library VALUES (18,cruise-3x1mi-T,"Cruise intervals (3×1 mi @ T)",threshold,"{5k,10k,hm,m}","{build,quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,T}",t,f,"[55,71)","[8,10]",1,"{""reps"": 3, ""type"": ""cruise_intervals"", ""recovery_sec"": 60, ""rep_pace_zone"": ""T"", ""rep_distance_m"": 1609, ""total_at_pace_mi"": 3}","3×1 mi @ T · 60s jog","WU 2 mi E, reps, CD 1.5 mi E. Even splits.","2 mi WU + 1.5 mi CD","Research/04-workout-vocabulary.md §5.3",t,"2026-05-31 03:40:10.218434+00");
INSERT INTO workout_library VALUES (19,cruise-4x1mi-T,"Cruise intervals (4×1 mi @ T)",threshold,"{10k,hm,m}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,T}",t,f,"[60,76)","[9,11]",1,"{""reps"": 4, ""type"": ""cruise_intervals"", ""recovery_sec"": 60, ""rep_pace_zone"": ""T"", ""rep_distance_m"": 1609, ""total_at_pace_mi"": 4}","4×1 mi @ T · 60s jog","Daniels cap: T at 10% weekly mileage. Even splits.",,"Research/04-workout-vocabulary.md §5.3",t,"2026-05-31 03:40:10.310119+00");
INSERT INTO workout_library VALUES (20,cruise-4x1km-T,"Cruise intervals (4×1km @ T)",threshold,"{5k,10k,hm}","{build,quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,T}",t,f,"[45,61)","[7,9]",1,"{""reps"": 4, ""type"": ""cruise_intervals"", ""recovery_sec"": 60, ""rep_pace_zone"": ""T"", ""rep_distance_m"": 1000, ""total_at_pace_mi"": 2.5}","4×1km @ T · 60s jog","10K-style cruise. Shorter reps, same T pace.",,"Research/04-workout-vocabulary.md §5.3",t,"2026-05-31 03:40:10.401156+00");
INSERT INTO workout_library VALUES (21,sub-threshold-5x1km,"Sub-threshold intervals (5×1km @ ST)",threshold,"{10k,hm,m}","{base,build,quality}","{advanced,advanced_plus}","{E,ST}",t,f,"[50,66)","[7,9]",2,"{""reps"": 5, ""type"": ""sub_threshold"", ""recovery_sec"": 75, ""rep_pace_zone"": ""ST"", ""rep_distance_m"": 1000, ""target_lactate_mmol"": [2.5, 3.5]}","5×1km @ ST (10-15 s/mi slower than T) · 75s jog","Norwegian sub-threshold. Pace discipline is everything — too hard collapses the model.",,"Research/04-workout-vocabulary.md §5.4",t,"2026-05-31 03:40:10.492113+00");
INSERT INTO workout_library VALUES (22,long-tempo-8,"Long tempo (8 mi @ HM-ish)",threshold,"{hm,m}",{race_specific},"{advanced,advanced_plus}","{E,HM,T}",t,t,"[75,91)","[10,12]",1,"{""type"": ""long_tempo"", ""blocks"": [{""label"": ""WU"", ""miles"": 1.5, ""pace_zone"": ""E""}, {""miles"": 8, ""pace_zone"": ""HM""}, {""label"": ""CD"", ""miles"": 1.5, ""pace_zone"": ""E""}]}","1.5 WU · 8 mi @ HM pace · 1.5 CD","Marathon-specific aerobic stress. ≥2 easy days after.",,"Research/04-workout-vocabulary.md §5.5",t,"2026-05-31 03:40:10.584553+00");
INSERT INTO workout_library VALUES (23,mile-repeats-4xI,"Mile repeats (4×1 mi @ I)",vo2max,"{5k,10k,hm}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,I}",t,f,"[60,81)","[8,10]",1,"{""reps"": 4, ""type"": ""vo2max_intervals"", ""recovery_min"": 3, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 1609, ""total_at_pace_mi"": 4}","4×1 mi @ I · 3 min jog","WU 2 mi E + drills + 2 strides. Hold even splits. Cap: 8% wkly mileage at I.","2 mi WU + 1 mi CD","Research/04-workout-vocabulary.md §6.2",t,"2026-05-31 03:40:10.674124+00");
INSERT INTO workout_library VALUES (24,mile-repeats-5xI,"Mile repeats (5×1 mi @ I)",vo2max,"{10k,hm}","{quality,race_specific}","{advanced,advanced_plus}","{E,I}",t,f,"[70,91)","[9,11]",1,"{""reps"": 5, ""type"": ""vo2max_intervals"", ""recovery_min"": 3, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 1609, ""total_at_pace_mi"": 5}","5×1 mi @ I · 3 min jog","Daniels classic. Daniels: ≤ 8% wkly mileage at I.",,"Research/04-workout-vocabulary.md §6.2",t,"2026-05-31 03:40:10.765304+00");
INSERT INTO workout_library VALUES (25,1k-repeats-5xI,"1000m repeats (5×1K @ I)",vo2max,"{5k,10k,hm}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,I}",t,f,"[55,71)","[7,9]",1,"{""reps"": 5, ""type"": ""vo2max_intervals"", ""recovery_sec"": 150, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 1000, ""total_at_pace_mi"": 3.1}","5×1km @ I · 2:30 jog","Ideal interval duration (~3–4 min) for max-out aerobic power.",,"Research/04-workout-vocabulary.md §6.3",t,"2026-05-31 03:40:10.85625+00");
INSERT INTO workout_library VALUES (26,1k-repeats-6xI,"1000m repeats (6×1K @ I)",vo2max,"{10k,hm}","{quality,race_specific}","{advanced,advanced_plus}","{E,I}",t,f,"[65,81)","[8,10]",1,"{""reps"": 6, ""type"": ""vo2max_intervals"", ""recovery_sec"": 150, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 1000, ""total_at_pace_mi"": 3.7}","6×1km @ I · 2:30 jog","Advanced dose. Hold pace.",,"Research/04-workout-vocabulary.md §6.3",t,"2026-05-31 03:40:10.947752+00");
INSERT INTO workout_library VALUES (27,800m-repeats-6xI,"800m repeats (6×800 @ I)",vo2max,"{5k,10k}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,I}",t,f,"[55,71)","[7,9]",1,"{""reps"": 6, ""type"": ""vo2max_intervals"", ""recovery_sec"": 150, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 800, ""total_at_pace_mi"": 3}","6×800m @ I · 2:30 jog","Classic 5K-specific. First rep should not be the fastest.",,"Research/04-workout-vocabulary.md §6.4",t,"2026-05-31 03:40:11.038601+00");
INSERT INTO workout_library VALUES (28,800m-repeats-8xI,"800m repeats (8×800 @ I)",vo2max,"{5k,10k}","{quality,race_specific}","{advanced,advanced_plus}","{E,I}",t,f,"[65,81)","[8,10]",1,"{""reps"": 8, ""type"": ""vo2max_intervals"", ""recovery_sec"": 150, ""rep_pace_zone"": ""I"", ""rep_distance_m"": 800, ""total_at_pace_mi"": 4}","8×800m @ I · 2:30 jog","5K specific peak. ~4 mi total at I.",,"Research/04-workout-vocabulary.md §6.4",t,"2026-05-31 03:40:11.128166+00");
INSERT INTO workout_library VALUES (29,yasso-800s-10,"Yasso 800s (10×800)",vo2max,{m},"{quality,race_specific}","{intermediate,advanced,advanced_plus}","{E,I}",t,f,"[70,91)","[9,11]",1,"{""reps"": 10, ""type"": ""yasso_800s"", ""pace_formula"": ""time per 800 (min:sec) = goal marathon (hr:min)"", ""rep_distance_m"": 800, ""recovery_match_time"": true}","10×800m · time matches goal marathon · equal jog rec","Final benchmark 10–14 days before goal marathon. Modern: VDOT prediction is more accurate but Yasso 800s still build VO2 well.",,"Research/04-workout-vocabulary.md §6.7",t,"2026-05-31 03:40:11.217461+00");
INSERT INTO workout_library VALUES (30,400m-repeats-12,"400m repeats (12×400 @ 5K)",vo2max,{5k},"{quality,race_specific,taper}","{intermediate,advanced,advanced_plus}","{E,5K,3K}",t,f,"[50,66)","[6,8]",1,"{""reps"": 12, ""type"": ""vo2max_intervals"", ""recovery_sec"": 90, ""rep_pace_zone"": ""5K"", ""rep_distance_m"": 400, ""total_at_pace_mi"": 3}","12×400 @ 5K pace · 90s jog","Edge between VO2 and speed. Use in 5K-specific phase.",,"Research/04-workout-vocabulary.md §6.6",t,"2026-05-31 03:40:11.308941+00");
INSERT INTO workout_library VALUES (31,strides-standalone,"Strides (6×80m standalone)",speed,{all},"{base,build,quality,race_specific,taper,race_week,maintenance}","{beginner,intermediate,advanced,advanced_plus}","{E,R}",f,f,"[20,31)","[2,4]",3,"{""type"": ""strides"", ""count"": 6, ""recovery"": ""full_walk"", ""distance_m"": 80}","2 mi E + 6×80m strides","Never stop doing strides. End of an easy run. Relaxed acceleration to mile-5K pace.",,"Research/04-workout-vocabulary.md §7.2",t,"2026-05-31 03:40:11.399556+00");
INSERT INTO workout_library VALUES (32,hill-sprints-8x10s,"Hill sprints (8×10s)",speed,{all},"{base,build,maintenance}","{intermediate,advanced,advanced_plus}",{R},f,f,"[25,41)","[3,5]",1,"{""reps"": 8, ""type"": ""hill_sprints"", ""recovery"": ""walk_down_full"", ""grade_pct"": [8, 15], ""duration_sec"": 10}","8×10s hill sprints (steep) · walk down full rec","Year-round. Especially valuable in base. Power, tendon stiffness, neuromuscular drive.",,"Research/04-workout-vocabulary.md §7.3",t,"2026-05-31 03:40:11.490488+00");
INSERT INTO workout_library VALUES (33,200m-repeats-10R,"200m repeats (10×200 @ R)",speed,"{5k,10k}","{base,race_specific,taper}","{intermediate,advanced,advanced_plus}","{E,R}",t,f,"[40,56)","[5,7]",1,"{""reps"": 10, ""type"": ""speed_repeats"", ""rep_pace_zone"": ""R"", ""rep_distance_m"": 200, ""total_at_pace_mi"": 1.25, ""recovery_distance_m"": 200}","10×200m @ R · 200m jog","Daniels: cap R at 5% weekly mileage. Mile pace.",,"Research/04-workout-vocabulary.md §7.4",t,"2026-05-31 03:40:11.581448+00");
INSERT INTO workout_library VALUES (34,hill-repeats-short-10x30s,"Short hill repeats (10×30s)",hills,{all},"{base,build}","{intermediate,advanced,advanced_plus}","{I,R}",t,f,"[40,56)","[5,7]",1,"{""reps"": 10, ""type"": ""hill_repeats"", ""recovery"": ""walk_jog_back"", ""grade_pct"": [4, 7], ""effort_pct"": 92, ""duration_sec"": 30}","10×30s hills (4–7% grade) · walk/jog back","Power + form. Gateway speed work.",,"Research/04-workout-vocabulary.md §8.2",t,"2026-05-31 03:40:11.672622+00");
INSERT INTO workout_library VALUES (35,hill-repeats-medium-6x90s,"Medium hill repeats (6×90s)",hills,{all},"{build,quality}","{intermediate,advanced,advanced_plus}","{10K,5K}",t,f,"[50,66)","[6,8]",1,"{""reps"": 6, ""type"": ""hill_repeats"", ""grade_pct"": [4, 6], ""pace_zones"": [""5K"", ""10K""], ""duration_sec"": 90, ""recovery_min"": 2.5}","6×90s hills @ 5K–10K effort · 2:30 jog down","Bridge between short hills and long hills.",,"Research/04-workout-vocabulary.md §8.3",t,"2026-05-31 03:40:11.763574+00");
INSERT INTO workout_library VALUES (36,hill-repeats-long-5x3min,"Long hill repeats (5×3 min)",hills,"{10k,hm,m}","{quality,race_specific}","{advanced,advanced_plus}","{T,10K}",t,f,"[60,81)","[7,9]",1,"{""reps"": 5, ""type"": ""hill_repeats"", ""recovery"": ""equal_time_jog"", ""grade_pct"": [3, 5], ""pace_zones"": [""T"", ""10K""], ""duration_sec"": 180}","5×3 min hills @ T–10K · equal jog down","VO2max with hill-strength stimulus. Reduces orthopedic stress vs flat intervals.",,"Research/04-workout-vocabulary.md §8.4",t,"2026-05-31 03:40:11.852874+00");
INSERT INTO workout_library VALUES (37,hill-fartlek-45,"Hill fartlek (45 min rolling)",hills,{all},"{base,build}","{intermediate,advanced,advanced_plus}","{E,T,10K}",t,f,"[40,56)","[5,7]",1,"{""type"": ""hill_fartlek"", ""surge_on"": ""climbs"", ""recovery_on"": ""descents_flats"", ""duration_min"": 45}","45 min hilly: surge every climb, recover descents","Continuous-run hill stimulus. 5–10 min total uphill surging.",,"Research/04-workout-vocabulary.md §8.6",t,"2026-05-31 03:40:11.942839+00");
INSERT INTO workout_library VALUES (38,mona-fartlek,"Mona fartlek (20 min)",fartlek,"{5k,10k,hm}","{base,build,quality}","{intermediate,advanced,advanced_plus}","{E,5K,3K}",t,f,"[50,66)","[6,8]",1,"{""type"": ""mona_fartlek"", ""pattern"": [{""reps"": 2, ""on_sec"": 90, ""off_sec"": 90, ""on_pace"": ""5K""}, {""reps"": 4, ""on_sec"": 60, ""off_sec"": 60, ""on_pace"": ""5K""}, {""reps"": 4, ""on_sec"": 30, ""off_sec"": 30, ""on_pace"": ""3K""}, {""reps"": 4, ""on_sec"": 15, ""off_sec"": 15, ""on_pace"": ""mile""}], ""total_at_pace_min"": 14, ""total_session_min"": 20}","Mona: 2×90s/90s + 4×60s/60s + 4×30s/30s + 4×15s/15s","Moneghetti / Wardlaw. Floats are recovery jogs, not stops. Keep effort honest.","15 min E each side","Research/04-workout-vocabulary.md §9.2",t,"2026-05-31 03:40:12.030998+00");
INSERT INTO workout_library VALUES (39,fartlek-6x3min,"Time fartlek (6×3 min on / 2 min off)",fartlek,"{5k,10k,hm,m}","{base,build,quality}","{intermediate,advanced,advanced_plus}","{E,10K,5K}",t,f,"[50,66)","[6,8]",1,"{""reps"": 6, ""type"": ""time_fartlek"", ""on_sec"": 180, ""off_sec"": 120, ""on_pace_zone"": ""10K""}","6×3 min @ 10K effort · 2 min easy jog","Structured pace play without a track. Good base-phase introduction.",,"Research/04-workout-vocabulary.md §9.5",t,"2026-05-31 03:40:12.121266+00");
INSERT INTO workout_library VALUES (40,mp-10k-alternations-6,"MP / 10K alternations (6×1 mi)",combo,{m},{race_specific},"{advanced,advanced_plus}","{MP,10K}",t,f,"[80,101)","[12,14]",1,"{""reps"": 6, ""type"": ""alternations"", ""total_mi"": 12, ""segment_a_mi"": 1, ""segment_b_mi"": 1, ""segment_a_pace"": ""MP"", ""segment_b_pace"": ""10K""}","6× (1 mi MP + 1 mi @ 10K) · continuous","Marathon-specific lactate clearance. Recoveries are MP — not easy.",,"Research/04-workout-vocabulary.md §10.1",t,"2026-05-31 03:40:12.210551+00");
INSERT INTO workout_library VALUES (41,wave-tempo-6mi,"Wave tempo (6 mi continuous, ±10 s around T)",combo,"{hm,m}",{race_specific},"{advanced,advanced_plus}","{E,T}",t,f,"[60,76)","[9,11]",1,"{""type"": ""wave_tempo"", ""total_mi"": 6, ""base_pace_zone"": ""T"", ""oscillation_sec_per_mi"": 10}","6 mi continuous wave tempo · ±10 s/mi around T","Average lands at T. Rhythmic, race-pace-skill.",,"Research/04-workout-vocabulary.md §10.3",t,"2026-05-31 03:40:12.302629+00");
INSERT INTO workout_library VALUES (42,canova-2k-repeats-5,"Canova 2K repeats (5×2K)",marathon_specific,{m},{race_specific},"{advanced,advanced_plus}","{MP,T}",t,f,"[80,101)","[11,13]",1,"{""reps"": 5, ""type"": ""canova_2k"", ""recovery_min"": 2, ""rep_distance_m"": 2000, ""pace_progression"": ""start slower than MP, descend to slightly faster than T""}","5×2K · descend MP → T · 2 min jog","Each rep ~2.5–5 s/km faster than the previous. Even pace within each rep.",,"Research/04-workout-vocabulary.md §11.2",t,"2026-05-31 03:40:12.391722+00");
INSERT INTO workout_library VALUES (43,mile-cutdowns-4,"Mile cutdowns (4×1 mi, descending)",cutdown,"{5k,10k,hm}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{MP,T,HM,5K}",t,f,"[60,76)","[8,10]",1,"{""reps"": 4, ""type"": ""cutdowns"", ""recovery_sec"": 75, ""rep_distance_m"": 1609, ""pace_progression"": [""MP"", ""HM"", ""T"", ""5K""]}","4×1 mi · MP → HM → T → 5K · 75s jog","Progressive load. Composure under fatigue. Final rep at 5K pace or faster.",,"Research/04-workout-vocabulary.md §12.2",t,"2026-05-31 03:40:12.480819+00");
INSERT INTO workout_library VALUES (44,ladder-400-800-1200-1600,"Ladder (400-800-1200-1600)",ladder,"{5k,10k}","{quality,race_specific}","{intermediate,advanced,advanced_plus}","{I,5K,3K,mile}",t,f,"[55,71)","[7,9]",1,"{""reps"": [{""pace_zone"": ""mile"", ""distance_m"": 400, ""recovery_sec"": 90}, {""pace_zone"": ""3K"", ""distance_m"": 800, ""recovery_sec"": 180}, {""pace_zone"": ""5K"", ""distance_m"": 1200, ""recovery_sec"": 240}, {""pace_zone"": ""10K"", ""distance_m"": 1600, ""recovery_sec"": 300}], ""type"": ""ladder_ascending""}","400 (mile) → 800 (3K) → 1200 (5K) → 1600 (10K)","Ascending ladder. Pace by rep length. Builds mental load.",,"Research/04-workout-vocabulary.md §13.2",t,"2026-05-31 03:40:12.572552+00");
INSERT INTO workout_library VALUES (45,race-spec-5k-12x400,"5K-specific: 12×400 at 5K pace",race_specific,{5k},{race_specific},"{intermediate,advanced,advanced_plus}",{5K},t,f,"[50,66)","[6,8]",1,"{""reps"": 12, ""type"": ""race_simulator"", ""recovery_sec"": 75, ""rep_pace_zone"": ""5K"", ""rep_distance_m"": 400}","12×400 @ 5K race pace · 60–90s jog","Classic 5K simulator. Tests race readiness.",,"Research/04-workout-vocabulary.md §14.1",t,"2026-05-31 03:40:12.662095+00");
INSERT INTO workout_library VALUES (46,race-spec-10k-4x2k,"10K-specific: 4×2K at 10K pace",race_specific,{10k},{race_specific},"{intermediate,advanced,advanced_plus}",{10K},t,f,"[65,81)","[8,10]",1,"{""reps"": 4, ""type"": ""race_simulator"", ""recovery_min"": 2.5, ""rep_pace_zone"": ""10K"", ""rep_distance_m"": 2000}","4×2K @ 10K race pace · 2:30 jog","10K race-pace specificity. Even splits.",,"Research/04-workout-vocabulary.md §14.2",t,"2026-05-31 03:40:12.752653+00");
INSERT INTO workout_library VALUES (47,race-spec-hm-4x2mi,"HM predictor: 4×2 mi at HM pace",race_specific,{hm},{race_specific},"{intermediate,advanced,advanced_plus}",{HM},t,f,"[85,106)","[11,13]",1,"{""reps"": 4, ""type"": ""race_simulator"", ""recovery_sec"": 90, ""rep_pace_zone"": ""HM"", ""rep_distance_m"": 3218}","4×2 mi @ HM pace · 60–120s jog","Classic HM readiness workout. Complete in control 2 wk before race = ready.",,"Research/04-workout-vocabulary.md §14.3",t,"2026-05-31 03:40:12.843282+00");
INSERT INTO workout_library VALUES (48,race-spec-hm-6x1mi,"HM volume: 6×1 mi at HM pace",race_specific,{hm},{race_specific},"{intermediate,advanced,advanced_plus}",{HM},t,f,"[70,91)","[10,12]",1,"{""reps"": 6, ""type"": ""race_simulator"", ""recovery_sec"": 60, ""rep_pace_zone"": ""HM"", ""rep_distance_m"": 1609}","6×1 mi @ HM pace · 60s jog","Mid-rep volume at HM. Short rests = high specificity.",,"Research/04-workout-vocabulary.md §14.3",t,"2026-05-31 03:40:12.933742+00");
INSERT INTO workout_library VALUES (49,base-building-easy-strides,"Base block: 6 mi E + 6×ST",base_building,{all},{base},"{intermediate,advanced,advanced_plus}","{E,R}",f,f,"[50,66)","[5,7]",2,"{""type"": ""easy_plus_strides"", ""miles"": 6, ""strides"": {""count"": 6, ""distance_m"": 80}}","6 mi E + 6×ST","Standard Lydiard-influenced base. Keep building aerobic capacity.",,"Research/22-plan-templates.md §6",t,"2026-05-31 03:40:13.024315+00");
INSERT INTO workout_library VALUES (50,maintenance-tempo-20min,"Maintenance tempo (20 min @ T)",maintenance,{all},{maintenance},"{intermediate,advanced,advanced_plus}","{E,T}",t,f,"[45,61)","[5,7]",1,"{""type"": ""continuous_tempo"", ""tempo_min"": 20, ""tempo_pace_zone"": ""T""}","20 min @ T (sandwiched in easy)","Between-cycle quality. Minimum-effective-dose: holds VO2max ~15 wk at 2/3 of training volume.",,"Research/22-plan-templates.md §7",t,"2026-05-31 03:40:13.116184+00");
INSERT INTO workout_library VALUES (51,race-week-shakeout,"Race-week shakeout (2 mi + 4×ST)",shakeout,{all},{race_week},"{beginner,intermediate,advanced,advanced_plus}","{E,R}",f,f,"[15,26)","[2,3]",1,"{""type"": ""shakeout"", ""miles"": 2, ""strides"": {""count"": 4, ""distance_m"": 80}}","2 mi E + 4×ST","Day before race. Loosen the legs. Final stride ~5–10 min before gun (race day).",,"Research/04-workout-vocabulary.md §17.3",t,"2026-05-31 03:40:13.208936+00");
INSERT INTO workout_library VALUES (52,race-week-rest,"Race-week rest",rest,{all},{race_week},"{beginner,intermediate,advanced,advanced_plus}",{},f,f,,"[0,0]",2,"{""type"": ""rest""}","Off — hydrate, fuel, sleep","2 days before race: full rest. Off feet.",,"Research/08-pacing-and-race-week.md §taper",t,"2026-05-31 03:40:13.299592+00");
INSERT INTO workout_library VALUES (53,walk-run-4-1,"Walk-run 4:1 (5 reps)",walk_run,{all},{base},{beginner},{E},f,f,"[20,31)","[1,3]",3,"{""reps"": 5, ""type"": ""walk_run"", ""pattern"": ""4 min walk / 1 min run""}","4 min walk / 1 min jog × 5","Return-to-run injury scaffold (minor severity). Pain ≥ 4/10 stops the session.",,"Research/05-injury-return-protocols.md §General-Principles",t,"2026-05-31 03:40:13.390313+00");
INSERT INTO workout_library VALUES (54,walk-run-2-3,"Walk-run 2:3 (5 reps)",walk_run,{all},{base},{beginner},{E},f,f,"[20,31)","[2,4]",3,"{""reps"": 5, ""type"": ""walk_run"", ""pattern"": ""2 min walk / 3 min run""}","2 min walk / 3 min jog × 5","Return-to-run progression. If 0 pain at end → progress to continuous next week.",,"Research/05-injury-return-protocols.md §General-Principles",t,"2026-05-31 03:40:13.481263+00");
